- name: stat
  stat:
    path: "/home/morix/develop/go-{{ go_version }}"
  register: g

- block:
  - name: download zip
    get_url:
      url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
      dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
  
  - name: mkdir GOPATH
    file:
      path: "/home/morix/develop/git/go"
      state: directory
      owner: morix
      group: morix
  
  - name: mkdir go directory
    file:
      path: "/home/morix/develop/go-{{ go_version }}"
      state: directory
      owner: morix
      group: morix
  
  - name: unarcheve
    unarchive:
      src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
      dest: "/home/morix/develop/go-{{ go_version }}"
      owner: morix
      group: morix
  
  - name: symlink
    file:
      src: "/home/morix/develop/go-{{ go_version }}/go"
      dest: "/home/morix/develop/go"
      state: link
  
  - name: add environment variable
    blockinfile:
      dest: "/home/morix/.bashrc"
      content: |
        export GOPATH=~/develop/git/go
        export PATH=${PATH}:${GOPATH}/bin:/home/morix/develop/go/bin

  when: not g.stat.exists

- name: download dep
  get_url:
    url: "https://github.com/golang/dep/releases/download/v{{ dep_version }}/dep-linux-amd64"
    dest: "/usr/local/bin/dep"
    owner: morix
    group: morix
    mode: 0755
