- name: get pubkey
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

- name: add source
  shell: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

- name: install chrome
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "google-chrome-stable"
