- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "curl"

- name: Check docker gpg key
  shell: apt-key fingerprint 0EBFCD88 | grep 0EBFCD88
  register: docker_gpg
  ignore_errors: True
  changed_when: False

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: docker_gpg | failed

- name: define lsb_release -cs
  shell: lsb_release -cs
  ignore_errors: True
  register: lsb_release

- name: set up the stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

- name: Install docker-ce
  apt:
    name: "docker-ce"
    update_cache: yes
  notify:
    - restart docker

- name: install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
